name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          build-dir: build
          args: -DCMAKE_BUILD_TYPE=Release
      - name: Run Hello World Test
        run: |
          ./build/hello_world_application/hello_world | grep -q "hello, world!"
          echo "Hello World test passed!"
      - name: Run Solver Test
        run: |
          echo "Testing equation solver:"
          OUTPUT=$(./build/solver_application/solver <<< "1 0 -25")
          echo "$OUTPUT"
          echo "$OUTPUT" | grep -q "x1 = -5.00000" || (echo "x1 test failed"; exit 1)
          echo "$OUTPUT" | grep -q "x2 = 5.00000" || (echo "x2 test failed"; exit 1)
          echo "Solver test passed!"

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          build-dir: build
          args: -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: Run Hello World Test
        run: |
          .\build\hello_world_application\Release\hello_world.exe | findstr "hello, world!"
          echo Hello World test passed!
      - name: Run Solver Test
        run: |
          echo Testing equation solver:
          set OUTPUT=
          for /f "delims=" %%i in ('echo 1 0 -25 ^| .\build\solver_application\Release\solver.exe') do set OUTPUT=%%i
          echo %OUTPUT%
          echo %OUTPUT% | findstr "x1 = -5.00000" || (echo x1 test failed & exit 1)
          echo %OUTPUT% | findstr "x2 = 5.00000" || (echo x2 test failed & exit 1)
          echo Solver test passed!